PROGRAM DECLINATION_BOUND
USE SUBS
USE OPTIMISATION_BOUND

IMPLICIT NONE


    REAL( KIND = EXTRA_LONG_REAL) :: OBS_COLAT, OBS_LONG, PHI_OBS
    INTEGER :: LMAX_B_OBS, LMAX_U, RESTRICTION
    INTEGER :: MINIM_FLAG
    CHARACTER(300) :: FILENAME
    REAL( KIND = 8) :: SCALE_FACTOR, TARGET_RMS, ETA

    REAL( KIND = EXTRA_LONG_REAL), ALLOCATABLE :: SPEC_U_TOR(:), SPEC_U_POL(:)
    REAL( KIND = EXTRA_LONG_REAL), ALLOCATABLE, DIMENSION(:) :: GAUSS


    PRINT*, 'ENTER COLAT/LONG (IN DEGREES) FOR OBSERVATION POINT'
    READ*, OBS_COLAT, OBS_LONG

    PHI_OBS = OBS_LONG * Pi / 180.0_8

    PRINT*, 'ENTER MAX DEGREE FOR U'
    READ*, LMAX_U

    PRINT*, 'ENTER MAX DEGREE FOR B_OBS'
    READ*, LMAX_B_OBS

    PRINT*, 'ENTER FILENAME FOR B_OBS: FORMAT SHOULD BE SINGLE LINE OF HEADER THEN GLM/HLM IN TABULAR FORMAT'
    READ*, FILENAME

    PRINT*, 'ENTER TARGET RMS VALUE FOR FLOW'
    READ*, TARGET_RMS

    PRINT*, 'ENTER SCALE FACTOR FOR ARROWS'
    READ*, SCALE_FACTOR


    PRINT*, 'RESTRICTION OF FLOW? 0: NONE, 1: POL ONLY, 2: TOR ONLY, 3: COLUMNAR'
    READ*, RESTRICTION

    PRINT*, 'ENTER ETA'
    READ*, ETA

    PRINT*, 'ENTER MINIMIZATION FLAG. 0: DIPOLE TILT; 1: INTENSITY AT OBSERVATION POINT; 2: INTENSITY CHANGE AT INTENSITY MINIMUM (SAA)'
    READ*, MINIM_FLAG
    
    
    CALL CALCULATE_OPTIMAL_FLOW(GAUSS, SPEC_U_TOR, SPEC_U_POL, OBS_COLAT, OBS_LONG, PHI_OBS, LMAX_U, LMAX_B_OBS, FILENAME, TARGET_RMS, SCALE_FACTOR, RESTRICTION, ETA, MINIM_FLAG)
    PRINT*, GAUSS(1),GAUSS(2),GAUSS(3)
STOP

 
END PROGRAM DECLINATION_BOUND
